version: '3.8'
services:
  db:
    image: postgres:13.1
    # just for local development
    environment:
      - POSTGRES_USER=aves
      - POSTGRES_PASSWORD=aves
      - POSTGRES_DB=aves
    ports:
      - 5432:5432
    volumes:
      - aves-db:/var/lib/postgresql/data/

volumes:
  aves-db:
