apiVersion: skaffold/v1
kind: Config
metadata:
  name: aves
build:
  artifacts:
    - image: dejankovacevic/aves
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/aves.yaml

profiles:
  # use the dockerfile profile to build images using Docker instead of Jib
  - name: dockerfile
    build:
      artifacts:
        - image: aves
          context: backend
