---
apiVersion: v1
kind: Service
metadata:
  name: aves
  namespace: staging
spec:
  selector:
    name: aves
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8090
      protocol: TCP
