---
apiVersion: v1
kind: Service
metadata:
  name: aves
  namespace: staging
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"aves-backendconfig"}}'
spec:
  selector:
    name: aves
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8090
      protocol: TCP
