ALTER TABLE Clients ADD COLUMN type VARCHAR;
ALTER TABLE Clients ADD COLUMN model VARCHAR;
ALTER TABLE Clients ADD COLUMN label VARCHAR;
ALTER TABLE Clients ADD COLUMN class VARCHAR;
ALTER TABLE Clients ADD COLUMN cookie VARCHAR;

ALTER TABLE Clients DROP COLUMN last;